<!DOCTYPE html>
<html>
   <head>
      <title>Welcome to myweb</title>
   </head>
   <body>
      <div id="site_container">
         <div id="header">
            <h1><strong>Welcome, </strong></h1><p>This is the header!</p>
         </div>
         <div id="content">
            <!-- Echo our content here! -->
            <?php echo $this->layout()->content; ?>
         </div>
         <div id="footer">
            <p>This is the footer!</p>
         </div>
      </div>
   </body>
</html>